In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')
movies.shape

(4803, 20)

In [3]:
movies=movies.merge(credits,on='title')
movies.shape

(4809, 23)

In [4]:
movies.original_language.unique()

array(['en', 'ja', 'fr', 'zh', 'es', 'ko', 'de', 'hi', 'ru', 'te', 'cn',
       'it', 'nl', 'ta', 'sv', 'th', 'da', 'xx', 'hu', 'cs', 'pt', 'is',
       'tr', 'nb', 'af', 'pl', 'he', 'ar', 'vi', 'ky', 'id', 'ro', 'fa',
       'no', 'sl', 'ps', 'el'], dtype=object)

In [5]:
movies.head(1).columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [6]:
# genres,id,keywords,title,overview,cast,crew

In [7]:
movies=movies[['genres','id','keywords','title','overview','cast','crew']]
movies.head(1)

,genres,id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
movies.isnull().sum()

genres      0
id          0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.duplicated().sum()

0

In [11]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
import ast

In [13]:
def convt(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [14]:
movies['genres']=movies.genres.apply(convt)
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
movies.iloc[1].keywords

'[{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic island"}, {"id": 1319, "name": "east india trading company"}, {"id": 2038, "name": "love of one\'s life"}, {"id": 2052, "name": "traitor"}, {"id": 2580, "name": "shipwreck"}, {"id": 2660, "name": "strong woman"}, {"id": 3799, "name": "ship"}, {"id": 5740, "name": "alliance"}, {"id": 5941, "name": "calypso"}, {"id": 6155, "name": "afterlife"}, {"id": 6211, "name": "fighter"}, {"id": 12988, "name": "pirate"}, {"id": 157186, "name": "swashbuckler"}, {"id": 179430, "name": "aftercreditsstinger"}]'

In [16]:

def keywords(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [17]:
keywords(movies.iloc[1].keywords)

['ocean',
 'drug abuse',
 'exotic island',
 'east india trading company',
 "love of one's life",
 'traitor',
 'shipwreck',
 'strong woman',
 'ship',
 'alliance',
 'calypso',
 'afterlife',
 'fighter',
 'pirate',
 'swashbuckler',
 'aftercreditsstinger']

In [18]:
movies['keywords']=movies.keywords.apply(keywords)

In [19]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies.iloc[1].cast

'[{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85, "name": "Johnny Depp", "order": 0}, {"cast_id": 5, "character": "Will Turner", "credit_id": "52fe4232c3a36847f800b511", "gender": 2, "id": 114, "name": "Orlando Bloom", "order": 1}, {"cast_id": 6, "character": "Elizabeth Swann", "credit_id": "52fe4232c3a36847f800b515", "gender": 1, "id": 116, "name": "Keira Knightley", "order": 2}, {"cast_id": 12, "character": "William \\"Bootstrap Bill\\" Turner", "credit_id": "52fe4232c3a36847f800b52d", "gender": 2, "id": 1640, "name": "Stellan Skarsg\\u00e5rd", "order": 3}, {"cast_id": 10, "character": "Captain Sao Feng", "credit_id": "52fe4232c3a36847f800b525", "gender": 2, "id": 1619, "name": "Chow Yun-fat", "order": 4}, {"cast_id": 9, "character": "Captain Davy Jones", "credit_id": "52fe4232c3a36847f800b521", "gender": 2, "id": 2440, "name": "Bill Nighy", "order": 5}, {"cast_id": 7, "character": "Captain Hector Barbossa", "credit_id": "52fe4232c3a36847f800b519", "gender": 2, "id": 118, "name": "Geoffrey Rush", "order": 6}, {"cast_id": 14, "character": "Admiral James Norrington", "credit_id": "52fe4232c3a36847f800b535", "gender": 2, "id": 1709, "name": "Jack Davenport", "order": 7}, {"cast_id": 13, "character": "Joshamee Gibbs", "credit_id": "52fe4232c3a36847f800b531", "gender": 2, "id": 2449, "name": "Kevin McNally", "order": 8}, {"cast_id": 11, "character": "Lord Cutler Beckett", "credit_id": "52fe4232c3a36847f800b529", "gender": 2, "id": 2441, "name": "Tom Hollander", "order": 9}, {"cast_id": 19, "character": "Tia Dalma", "credit_id": "52fe4232c3a36847f800b549", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 10}, {"cast_id": 8, "character": "Governor Weatherby Swann", "credit_id": "52fe4232c3a36847f800b51d", "gender": 2, "id": 378, "name": "Jonathan Pryce", "order": 11}, {"cast_id": 37, "character": "Captain Teague Sparrow", "credit_id": "52fe4232c3a36847f800b5b3", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 12}, {"cast_id": 16, "character": "Pintel", "credit_id": "52fe4232c3a36847f800b53d", "gender": 2, "id": 1710, "name": "Lee Arenberg", "order": 13}, {"cast_id": 15, "character": "Ragetti", "credit_id": "52fe4232c3a36847f800b539", "gender": 2, "id": 1711, "name": "Mackenzie Crook", "order": 14}, {"cast_id": 18, "character": "Lieutenant Theodore Groves", "credit_id": "52fe4232c3a36847f800b545", "gender": 2, "id": 4031, "name": "Greg Ellis", "order": 15}, {"cast_id": 55, "character": "Cotton", "credit_id": "57e28d2ec3a3681a01005b5c", "gender": 2, "id": 1715, "name": "David Bailie", "order": 16}, {"cast_id": 17, "character": "Marty", "credit_id": "52fe4232c3a36847f800b541", "gender": 2, "id": 4030, "name": "Martin Klebba", "order": 17}, {"cast_id": 57, "character": "Ian Mercer", "credit_id": "57e28d78c3a36808b900bf4f", "gender": 0, "id": 939, "name": "David Schofield", "order": 18}, {"cast_id": 62, "character": "Scarlett", "credit_id": "57e28ec5c3a3681a50005855", "gender": 1, "id": 2450, "name": "Lauren Maher", "order": 19}, {"cast_id": 63, "character": "Giselle", "credit_id": "57e28ed692514123f5005635", "gender": 1, "id": 2452, "name": "Vanessa Branch", "order": 20}, {"cast_id": 60, "character": "Mullroy", "credit_id": "57e28db2c3a3681a01005bc7", "gender": 2, "id": 1714, "name": "Angus Barnett", "order": 21}, {"cast_id": 59, "character": "Murtogg", "credit_id": "57e28da192514118f7006008", "gender": 0, "id": 1713, "name": "Giles New", "order": 22}, {"cast_id": 58, "character": "Tai Huang", "credit_id": "57e28d8ec3a3681a01005bab", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 23}, {"cast_id": 64, "character": "Henry Turner", "credit_id": "57e29119925141151100a6cc", "gender": 2, "id": 61259, "name": "Dominic Scott Kay", "order": 24}, {"cast_id": 39, "character": "Mistress Ching", "credit_id": "52fe4232c3a36847f800b5bd", "gender": 1, "id": 33500, "name": "Takayo Fischer", "order": 25}, {"cast_id": 40, "character": "Lieutenant Greitzer", "credit_id": "52fe4232c3a36847f800b5c1", "gender": 2, "id": 1224149, "name": "David Meunier", "order": 26}, {"cast_id": 49, "character": "Hadras", "credit_id": "56d1871c92514174680010cf", "gender": 2, "id": 429401, "name": "Ho-Kwan Tse", "order": 27}, {"cast_id": 56, "character": "Clacker", "credit_id": "57e28d4b92514125710055cb", "gender": 0, "id": 1123, "name": "Andy Beckwith", "order": 28}, {"cast_id": 51, "character": "Penrod", "credit_id": "56ec8c14c3a3682260003c53", "gender": 2, "id": 1056117, "name": "Peter Donald Badalamenti II", "order": 29}, {"cast_id": 61, "character": "Cotton\'s Parrot (voice)", "credit_id": "57e28dcc9251412463005678", "gender": 2, "id": 21700, "name": "Christopher S. Capp", "order": 30}, {"cast_id": 65, "character": "Captain Teague", "credit_id": "58bc2a37c3a368663003740b", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 31}, {"cast_id": 66, "character": "Captain Jocard", "credit_id": "58bc2a8e925141609e03a179", "gender": 2, "id": 2603, "name": "Hakeem Kae-Kazim", "order": 32}, {"cast_id": 67, "character": "Captain Ammand", "credit_id": "58e2a21ac3a36872af00f9c2", "gender": 0, "id": 70577, "name": "Ghassan Massoud", "order": 33}]'

In [21]:
def cast(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L[0:3]

In [22]:
cast(movies.iloc[1].cast)

['Johnny Depp', 'Orlando Bloom', 'Keira Knightley']

In [23]:
movies['cast']=movies.cast.apply(cast)

In [24]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies.cast.value_counts

<bound method IndexOpsMixin.value_counts of 0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, LÃ©a Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry BishÃ©, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object>

In [26]:
movies.iloc[1].crew

'[{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photography", "name": "Dariusz Wolski"}, {"credit_id": "52fe4232c3a36847f800b4fd", "department": "Directing", "gender": 2, "id": 1704, "job": "Director", "name": "Gore Verbinski"}, {"credit_id": "52fe4232c3a36847f800b54f", "department": "Production", "gender": 2, "id": 770, "job": "Producer", "name": "Jerry Bruckheimer"}, {"credit_id": "52fe4232c3a36847f800b503", "department": "Writing", "gender": 2, "id": 1705, "job": "Screenplay", "name": "Ted Elliott"}, {"credit_id": "52fe4232c3a36847f800b509", "department": "Writing", "gender": 2, "id": 1706, "job": "Screenplay", "name": "Terry Rossio"}, {"credit_id": "52fe4232c3a36847f800b57f", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "52fe4232c3a36847f800b585", "department": "Editing", "gender": 2, "id": 1722, "job": "Editor", "name": "Craig Wood"}, {"credit_id": "52fe4232c3a36847f800b573", "department": "Sound", "gender": 2, "id": 947, "job": "Original Music Composer", "name": "Hans Zimmer"}, {"credit_id": "52fe4232c3a36847f800b555", "department": "Production", "gender": 2, "id": 2444, "job": "Executive Producer", "name": "Mike Stenson"}, {"credit_id": "52fe4232c3a36847f800b561", "department": "Production", "gender": 2, "id": 2445, "job": "Producer", "name": "Eric McLeod"}, {"credit_id": "52fe4232c3a36847f800b55b", "department": "Production", "gender": 2, "id": 2446, "job": "Producer", "name": "Chad Oman"}, {"credit_id": "52fe4232c3a36847f800b567", "department": "Production", "gender": 0, "id": 2447, "job": "Producer", "name": "Peter Kohn"}, {"credit_id": "52fe4232c3a36847f800b56d", "department": "Production", "gender": 0, "id": 2448, "job": "Producer", "name": "Pat Sandston"}, {"credit_id": "52fe4232c3a36847f800b58b", "department": "Production", "gender": 1, "id": 2215, "job": "Casting", "name": "Denise Chamian"}, {"credit_id": "52fe4232c3a36847f800b597", "department": "Art", "gender": 2, "id": 1226, "job": "Production Design", "name": "Rick Heinrichs"}, {"credit_id": "52fe4232c3a36847f800b59d", "department": "Art", "gender": 2, "id": 553, "job": "Art Direction", "name": "John Dexter"}, {"credit_id": "52fe4232c3a36847f800b591", "department": "Production", "gender": 1, "id": 3311, "job": "Casting", "name": "Priscilla John"}, {"credit_id": "52fe4232c3a36847f800b5a3", "department": "Art", "gender": 1, "id": 4032, "job": "Set Decoration", "name": "Cheryl Carasik"}, {"credit_id": "52fe4232c3a36847f800b5a9", "department": "Costume & Make-Up", "gender": 0, "id": 4033, "job": "Costume Design", "name": "Liz Dann"}, {"credit_id": "52fe4232c3a36847f800b5af", "department": "Costume & Make-Up", "gender": 1, "id": 4034, "job": "Costume Design", "name": "Penny Rose"}, {"credit_id": "56427ce8c3a3686a53000d8b", "department": "Sound", "gender": 2, "id": 5132, "job": "Music Supervisor", "name": "Bob Badami"}, {"credit_id": "55993c15c3a36855db002f33", "department": "Art", "gender": 2, "id": 146439, "job": "Conceptual Design", "name": "James Ward Byrkit"}, {"credit_id": "52fe4232c3a36847f800b5b9", "department": "Costume & Make-Up", "gender": 1, "id": 406204, "job": "Makeup Department Head", "name": "Ve Neill"}, {"credit_id": "56e47f7892514132690017bd", "department": "Crew", "gender": 2, "id": 1259516, "job": "Stunts", "name": "John Dixon"}, {"credit_id": "5740be639251416597000849", "department": "Crew", "gender": 0, "id": 1336716, "job": "CGI Supervisor", "name": "Dottie Starling"}, {"credit_id": "56427c639251412fc8000dc1", "department": "Directing", "gender": 1, "id": 1344278, "job": "Script Supervisor", "name": "Pamela Alch"}, {"credit_id": "57083101c3a3681d320004e6", "department": "Crew", "gender": 0, "id": 1368867, "job": "Special Effects Coordinator", "name": "Allen Hall"}, {"credit_id": "56427d5ec3a3686a62000d4a", "department": "Sound", "gender": 0, "id": 1368884, "job": "Music Editor", "name": "Melissa Muik"}, {"credit_id": "56427c7b9251412fd4000e07", "department": "Directing", "gender": 1, "id": 1395290, "job": "Script Supervisor", "name": "Sharron Reynolds"}, {"credit_id": "56427d2bc3a3686a53000d9b", "department": "Sound", "gender": 0, "id": 1399327, "job": "Music Editor", "name": "Barbara McDermott"}, {"credit_id": "56427cb4c3a3686a53000d87", "department": "Directing", "gender": 1, "id": 1400738, "job": "Script Supervisor", "name": "Karen Golden"}, {"credit_id": "56427d169251412fd4000e23", "department": "Sound", "gender": 0, "id": 1534197, "job": "Music Editor", "name": "Katie Greathouse"}]'

In [27]:
def director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
    return L

In [28]:
director(movies.iloc[1].crew)

['Gore Verbinski']

In [29]:
movies['crew']=movies.crew.apply(director)

In [30]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
movies['overview']=movies.overview.apply(lambda x:x.split())

In [32]:
movies.head()

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [33]:
movies['genres']=movies.genres.apply(lambda x: [i.replace(" ",'') for i in x])
movies['crew']=movies.crew.apply(lambda x: [i.replace(" ",'') for i in x])
movies['cast']=movies.cast.apply(lambda x: [i.replace(" ",'') for i in x])

movies['keywords']=movies.keywords.apply(lambda x: [i.replace(" ",'') for i in x])

In [34]:
movies.head(1)

,genres,id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]

In [35]:
movies['tags']= movies.crew + movies.cast + movies.genres+ movies.overview + movies.keywords
movies.head()

,genres,id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[JamesCameron, SamWorthington, ZoeSaldana, Sig..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[GoreVerbinski, JohnnyDepp, OrlandoBloom, Keir..."
2,"[Action, Adventure, Crime]",206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[SamMendes, DanielCraig, ChristophWaltz, LÃ©aSe..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[ChristopherNolan, ChristianBale, MichaelCaine..."
4,"[Action, Adventure, ScienceFiction]",49529,"[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[AndrewStanton, TaylorKitsch, LynnCollins, Sam..."

In [36]:
new_df=movies[['id','title','tags']]
new_df.head(1)

      id   title                                               tags
0  19995  Avatar  [JamesCameron, SamWorthington, ZoeSaldana, Sig...

In [37]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\user\AppData\Local\Temp\ipykernel_3856\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [38]:
new_df.iloc[0].tags

'JamesCameron SamWorthington ZoeSaldana SigourneyWeaver Action Adventure Fantasy ScienceFiction In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

In [39]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())
new_df.head(1)

C:\Users\user\AppData\Local\Temp\ipykernel_3856\1901767957.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

      id   title                                               tags
0  19995  Avatar  jamescameron samworthington zoesaldana sigourn...

In [40]:
new_df.head()

,id,title,tags
0,19995,Avatar,jamescameron samworthington zoesaldana sigourn...
1,285,Pirates of the Caribbean: At World's End,goreverbinski johnnydepp orlandobloom keirakni...
2,206647,Spectre,sammendes danielcraig christophwaltz lÃ©aseydou...
3,49026,The Dark Knight Rises,christophernolan christianbale michaelcaine ga...
4,49529,John Carter,andrewstanton taylorkitsch lynncollins samanth...

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [42]:
vectors=cv.fit_transform(new_df['tags']).toarray()
vectors.shape

(4806, 5000)

In [43]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
cv.get_feature_names()

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'ann',
 'anna',
 'annabelle',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'anonymous',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'atlantic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breast',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'chloÃ«sevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colombia',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'constant',
 'constantly',
 'construction',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 ...]

In [45]:
import nltk

In [46]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [47]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [48]:
new_df['tags']=new_df['tags'].apply(stem)
new_df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_3856\4140110386.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

,id,title,tags
0,19995,Avatar,jamescameron samworthington zoesaldana sigourn...
1,285,Pirates of the Caribbean: At World's End,goreverbinski johnnydepp orlandobloom keirakni...
2,206647,Spectre,sammend danielcraig christophwaltz lÃ©aseydoux ...
3,49026,The Dark Knight Rises,christophernolan christianbal michaelcain gary...
4,49529,John Carter,andrewstanton taylorkitsch lynncollin samantha...

In [49]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [50]:
sorted(list(enumerate(similarity[2])),reverse=True,key=lambda x : x[1])[0:6]

[(2, 1.0000000000000002),
 (11, 0.373878250552983),
 (1346, 0.3507392801587168),
 (29, 0.30179727289671415),
 (3166, 0.28138742976632514),
 (4077, 0.27824333745610097)]

In [51]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x : x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [52]:
new_df[new_df['title']=='Batman'].index[0]

1362

In [53]:
new_df.iloc[40].title

'Cars 2'

In [54]:
recommend('Cars 2')

Cars
The Croods
The Adventures of Rocky & Bullwinkle
Ice Age: Continental Drift
Alpha and Omega: The Legend of the Saw Tooth Cave

In [55]:
import pickle
pickle.dump(new_df,open('movies.pkl','wb'))

In [56]:
import pickle
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [57]:
pickle.dump(similarity,open('similarity','wb'))